"""Init migration

Revision ID: fcbe02100199
Revises: 
Create Date: 2023-10-12 20:22:22.811413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbe02100199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('jservice_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.String(length=511), nullable=True),
    sa.Column('question_answer', sa.String(length=511), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_created_at', sa.DateTime()),
    sa.Column('question_airdate', sa.DateTime()),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_jservice_id'), ['jservice_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_jservice_id'))

    op.drop_table('questions')
    # ### end Alembic commands ###
